name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install tox==4.* tox-gh-actions==3.*
    - name: Run tox
      run: tox
    - name: System test
      env:
        SC_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: ./test/system_test/system_test.sh
